import Head from 'next/head'
import Hero from '../components/Hero'
import NavBar from '../components/NavBar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <NavBar />

      <main>
        <Hero />
        <div className='content'>
          <div className='callout'>
            <h1>What is a Gift 'n Grow Gift Bag, Gift Box or Gift Tag?</h1>
            <div className='bordered-image'>
              <img
                alt=''
                src='App_Themes/default/images/passiton.jpg'
              />
            </div>
            <p>
              <span style={{ fontSize: 16 }}>
                It's an eco-friendly, 100% recycled paper gift bag or recycled
                gift box that is made in the USA. As an added feature, you are
                able to track your bag or box's journey online. &nbsp;It's also
                a fun way to help the environment and to see the positive impact
                you can make by reducing paper waste. &nbsp;Inside every bag or
                box, you'll find &nbsp;an I.D. code. Use it to log into our
                website and participate in your bag's or box's journey. We now
                have gift tags that grow... wildflowers!!!!
              </span>
            </p>
            <p>
              <a href='http://www.giftngrow.com/passiton.aspx'>Learn more</a>
            </p>
            <p>&nbsp;</p>
            <p>
              <span
                className='Apple-style-span'
                style={{ fontSize: 14 }}
              >
                <b>
                  <br />
                </b>
              </span>
            </p>
          </div>
          <div className='callout'>
            <h1>10% of net profits donated to plant trees!</h1>
            <div className='bordered-image'>
              <img
                alt=''
                src='App_Themes/default/images/tree.jpg'
              />
            </div>
            <p>
              <span style={{ fontSize: 16 }}>
                Purchasing a 100% recycled Gift 'n Grow gift bag or recycled
                gift box saves trees, water, landfill space, oil and
                electricity. Passing it on helps even more.&nbsp;
              </span>
            </p>
            <p>
              <span
                className='Apple-style-span'
                style={{ fontSize: 16 }}
              >
                Gift 'n Grow takes it another step further and makes your gift
                grow by donating a full 10% of net profits to forestry
                organizations for new tree plantings. &nbsp;The recycled gift
                bags and recycled gift boxes that keep on giving.
              </span>
            </p>
            <p>
              <a href='/PlantingTrees.aspx'>Learn More</a>
            </p>
            <p>&nbsp;</p>
            <p>&nbsp;</p>
            <p style={{ marginBottom: 10 }}>
              <span style={{ fontSize: 14 }}>
                <strong>Wholesale Opportunities:</strong>
              </span>
            </p>
            <p style={{ marginBottom: 10 }}>
              You too can encourage your customer to purchase with a pupose, by
              offering our recycled gift bags and recycled gift boxes and gift
              tags that grow! More people are looking for ways to "Go Green" and
              "Gift 'n Grow" does that with our eco-friendly gift bags,
              eco-friendly gift boxes and tags. All made in the USA. Your
              customers will also enjoy tracking their gift bag's or gift box's
              journey online as it makes its way around the neighborhood, city,
              state, or country. They are available in a variety of sizes and
              designs and are perfect for any occasion.&nbsp;
            </p>
          </div>
        </div>
      </main>

      <footer>
        <div id='footer-contact'>
          <img
            src='/App_Themes/default/images/logo_footer.png'
            alt="Gift 'n Grow"
          />
          <h3>Gift 'n Grow</h3>
          <p>
            P.O. Box 180553
            <br />
            Delafield, WI 53018
            <br />
            terri@giftngrow.com
          </p>
          <img
            className='Gbsoa'
            src='/App_Themes/default/images/GreenBusinessSealofApprovalTiny.gif'
            alt='Green Business Seal of Approval'
          />
        </div>
        <ul id='menu'>
          <li>
            <a href='https://www.giftngrow.com/about-us.aspx'>About Us</a>
          </li>
          <li>
            <a href='https://www.giftngrow.com/terms.aspx'>
              Terms and Conditions
            </a>
          </li>
          <li>
            <a href='https://www.giftngrow.com/privacy-policy.aspx'>
              Privacy Policy
            </a>
          </li>
          <li>
            <a href='/ContactUs.aspx'>Contact Us</a>
          </li>
        </ul>
        <p>Copyright © 2010 Gift ‘n Grow. All rights reserved.</p>
        <p>
          <a
            href='http://www.facebook.com/pages/Gift-n-Grow/155791191130981'
            target='_blank'
          >
            <img src='/App_Themes/default/images/social/Facebook.png' />
          </a>
        </p>
      </footer>
    </div>
  )
}
