import Head from 'next/head'
import { ReactNode } from 'react'
import Footer from './Footer'
import NavBar from './NavBar'
import { OneTap } from './OneTap'

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <OneTap />
      <NavBar />
      {children}
      <Footer />
    </>
  )
}
